dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("profile/", views.profile, name="profile"),
    path("editer-le-profil/<int:pk>", views.updateProfile, name="update-profile"),
]

delivry/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]


urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("", include("main.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("account/", include("account.urls")),
    path("colis/", include("packages.urls")),
    path("ramassage/", include("pickup.urls")),
    path("factures/", include("invoices.urls")),
    path("suivi-colis/", include("tracking.urls")),
    path("les-bons-de-commandes/", include("boxPackages.urls")),
    path("dashboard/nous-contacter/", include("contactUs.urls")),
    path("dashboard-admin/", include("adminManager.urls")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = "helpers.views.page_404"

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("les-villes", views.allCitys, name="all_citys"),
]

dashboard/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
from main.models import *
from django.utils import timezone


# Create your models here.

class Profile(models.Model):
    TYPEBANK = (
        ("CIH", "CIH"),
        ("Al Barid Bank", "Al Barid Bank"),
        ("Attijariwafa Bank", "Attijariwafa Bank"),
        ("BMCE", "BMCE"),
        ("Société générale", "Société générale"),
    )
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, unique=True, null=True, blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    business_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=50, )
    address = models.CharField(max_length=100)
    bank = models.CharField(max_length=50, choices=TYPEBANK)
    rip = models.CharField(max_length=27)
    total_money_net = models.IntegerField(blank=True, null=True, default=0)
    image = models.ImageField(upload_to="profiles/%Y/%m/%d", null=True, blank=True)

    DisplayFields = ["id", "first_name", "last_name", "business_name", "phone", "address", "bank", "rip", "total_money_net"]
    SearchbleFields = ["first_name", "last_name", "business_name", "phone"]

    def __str__(self):
        return self.first_name

class Setting(models.Model):
    title = models.CharField(max_length=50)
    topic = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)

    DisplayFields = ["id", "title", "topic", "date"]
    SearchbleFields = ["title", "topic", "date"]

    def __str__(self):
        return self.title

pickup/models.py
from django.db import models
from packages.models import *
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Received(models.Model):
    received_id = models.CharField(max_length=100, default='None', null=True, blank=True)
    date_received = models.CharField(max_length=100, null=True, blank=True)
    packages = models.ManyToManyField(NewPackage, blank=True)
    total_amount = models.IntegerField(null=True, blank=True)
    total_withdrawn = models.IntegerField(null=True, blank=True)
    receive = models.BooleanField(null=True, blank=True, default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    invoise = models.BooleanField(null=True, blank=True, default=False)

    DisplayFields = ["id", "received_id", "total_amount", "total_withdrawn", "receive", "user", "invoise", "date_received"]
    SearchbleFields = ["received_id"]

    def __str__(self):
        return self.received_id

dashboard/forms.py
from django.forms import ModelForm
from .models import *

class NewProfile(ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import *
from .models import *
from packages.models import *
from pickup.models import *
from main.models import *
from .statistics_1 import countCitys
from account.decorators import *
from django.contrib import messages
from django.utils.translation import gettext as _
from invoices.views import calc
# Create your views here.


@login_required(login_url="connexion")
@admins_only
def dashboard(request):

    parcel_inv = Received.objects.filter(user=request.user, invoise=True)
    
    # calc factur
    calc(parcel_inv)

    
    # data nav bar
    settings = Setting.objects.all()  # icon settings
    profileImage = Profile.objects.filter(user=request.user)  # icon profile

    # data statistics withe DATE
    packages = NewPackage.objects.filter(user=request.user)
    listCityPack = []
    listDatePack = []
    for pack in packages:
        listCityPack.append(pack.city)
        listDatePack.append(pack.date_created)

    # data statistics withe city
    listCity = []
    listCityCount = []
    for p in listCityPack:
        result = countCitys(listCityPack, p)
        if p not in listCity:
            listCity.append(p)
            listCityCount.append(result)

    # data statistics withe days
    listDays = []
    listDaysCount = []
    for d in listDatePack:
        result = countCitys(listDatePack, d)
        if d not in listDays:
            listDays.append(d)
            listDaysCount.append(result)
    

    package_no_invoices = Received.objects.filter(
        user=request.user, invoise=False)
    package_invoices = Received.objects.filter(user=request.user, invoise=True)

    # Total packages returned 
    packages_return = NewPackage.objects.filter(
        user=request.user)
    pack_list_returned = []
    for p_r in packages_return:
        if p_r.etat == "Returned/Cancelled" or p_r.etat == "Go back/Exchange" or p_r.etat == "Returned/Refused":
            pack_list_returned.append(p_r)

            
    TOTAL_NET_INCOME = 0
    try:
        # calc total net 
        profileMoney = Profile.objects.get(user=request.user)
        profileMoney.total_money_net = 0
        for pack_inv in package_invoices:
            profileMoney.total_money_net += pack_inv.total_amount
        
        TOTAL_NET_INCOME = profileMoney.total_money_net
        profileMoney.save()
    except:
        pass
    ############# end #############


    context = {
        "pack_list_returned": len(pack_list_returned),
        "package_no_invoices": package_no_invoices.count(),
        "package_invoices": package_invoices.count(),
        "TOTAL_NET_INCOME": TOTAL_NET_INCOME,
        "latest_packages": list(packages_return)[-10:],
        "parcel_inv": parcel_inv,
        "settings": settings,
        "profileImage": profileImage,
        "listCity":listCity,
        "listCityCount":listCityCount,
        "listDays":listDays,
        "listDaysCount":listDaysCount,
    }
    return render(request, "dashboard/dashboard.html", context)


@login_required(login_url="connexion")
@allowedUsers(allowedGroups=["customer"])
def profile(request):
    # data nav bar
    settings = Setting.objects.all()  # icon settings
    profileImage = Profile.objects.filter(user=request.user)  # icon profile


    form = NewProfile()
    if request.method == "POST":
        form = NewProfile(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = User.objects.get(id=request.user.id)
            obj.save()
            return redirect("profile")
    data = {}
    try:
        info = Profile.objects.get(user=request.user)
        data = {
            'firstname': info.first_name,
            'lastname': info.last_name,
            'business_name': info.business_name,
            'phone': info.phone,
            'address': info.address,
            'bank': info.bank,
            'rip': info.rip,
        }
    except:
        pass

    context = {
        "form": form,
        "data": data,
        "settings": settings,
        "profileImage": profileImage,
    }
    return render(request, "dashboard/pages/profile.html", context)


@login_required(login_url="connexion")
@allowedUsers(allowedGroups=["customer"])
def updateProfile(request, pk):
    
    # data nav bar
    settings = Setting.objects.all()  # icon settings
    profileImage = Profile.objects.filter(user=request.user)  # icon profile

    _profile = Profile.objects.get(user=pk)
    form = NewProfile(instance=_profile)
    if request.method == "POST":
        form = NewProfile(request.POST, request.FILES, instance=_profile)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = User.objects.get(id=request.user.id)
            obj.save()
            return redirect("profile")
    data = {}
    info = Profile.objects.filter(user=request.user)
    for i in info:
        data = {
            'firstname': i.first_name,
            'lastname': i.last_name,
            'business_name': i.business_name,
            'phone': i.phone,
            'address': i.address,
            'bank': i.bank,
            'rip': i.rip,
        }

    context = {
        "form": form,
        "data": data,
        "settings": settings,
        "profileImage": profileImage,
    }
    return render(request, "dashboard/pages/update-profile.html", context)

templates/dashboard-admin/add_packages.html
{% extends 'dashboard-admin/dashboard.html' %}
{% load static %}

{% block content %}
    <div class="dashboard">
        <div class="content">
            <div class="block container mt-5 ">
                <div class="row justify-content-center received">
                    <form class="row g-3 col-12" method="POST">
                        {% csrf_token %}
                        <div class="col-md-12 mb-4">
                            <label for="inputPackages" class="form-label">Men-Delivery</label>
                            <select name="man_delivery" class="form-select" id="id_man_delivery">
                                {% for item in data_admin_delivery %}
                                    {% for man in item.men_delivery.all %}
                                        <option value="{{man.id}}">{{man}}</option>
                                    {% endfor %}
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-md-12 mb-4">
                            <label for="inputPackages" class="form-label">Packages</label>
                            <select name="set_packages" class="form-select" multiple id="id_set_packages">
                                {% for item in data_admin_delivery %}
                                    {% for package in item.packages.all %}
                                        {% if packages_deli %}
                                            {% for packDeli in packages_deli %}
                                                {% for pack in packDeli.set_packages.all %}
                                                    {% if package != pack %}
                                                        <option value="{{package.id}}">{{package.id_package}} - {{package.address}} - {{package.city}}</option>
                                                    {% endif %}
                                                {% endfor %}
                                            {% endfor %}
                                        {% else %}
                                        <option value="{{package.id}}">{{package.id_package}} - {{package.address}} - {{package.city}}</option>
                                        {% endif %}
                                    {% endfor %}
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-outline-success col-12">Send</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

<script>
    $(document).ready(function () {
        $('#id_man_delivery').selectize({
            sortField: 'text',
            delimiter: " - ",
        });
        $('#id_set_packages').selectize({
            sortField: 'text',
        });
    });
</script>

{% endblock content %}

templates/dashboard-admin/add_profile_delivery.html
{% extends 'dashboard-admin/dashboard.html' %}
{% load static %}


{% block content %}
    <div class="dashboard">
        <div class="content">
            <div class="block container mt-5 ">
                <div class="row justify-content-center add-man-delivery">
                    <form class="row g-3 col-9" method="POST">
                        {% csrf_token %}
                        <!-- <input type="text" name="user" id="user" class="form-control" placeholder="Username" hidden> -->
                        <div class="col-md-4 mb-4">
                            <label for="inputArticle" class="form-label">Username</label>
                            <input type="text" name="username" id="username" class="form-control" placeholder="Username">
                        </div>
                        <div class="col-md-4 mb-4">
                            <label for="inputId" class="form-label">First Name</label>
                            <input type="text" name="first_name" class="form-control" placeholder="First name">
                        </div>
                        <div class="col-md-4 mb-4">
                            <label for="inputArticle" class="form-label">Last Name</label>
                            <input type="text" name="last_name" class="form-control" placeholder="Last name">
                        </div>
                        <div class="col-12 mb-4">
                            <label for="inputAddress" class="form-label">Email</label>
                            <input type="email" name="email" class="form-control" placeholder="Email">
                        </div>
                        <div class="col-md-6 mb-4">
                            <label for="inputCity" class="form-label">City</label>
                            <input type="text" name="city" class="form-control" placeholder="City">
                        </div>
                        <div class="col-6 mb-4">
                            <label for="inputnumber" class="form-label">Phone number</label>
                            <input type="tel" name="phone_number" class="form-control" placeholder="Phone Number">
                        </div>
                        <div class="col-md-6 mb-4">
                            <label for="inputCity" class="form-label">Password</label>
                            <input type="password" name="password1" class="form-control" placeholder="Password">
                        </div>
                        <div class="col-6 mb-4">
                            <label for="inputnumber" class="form-label">Password Again</label>
                            <input type="password" name="password2" class="form-control" placeholder="Password Again">
                        </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-outline-success col-12">Add</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<!-- <script>
    const username = document.getElementById("username");
    const user = document.getElementById("user");
    username.addEventListener("input", _ => {
        user.value = username.value
    })

</script> -->
{% endblock content %}

templates/dashboard-admin/admin_men_delivery.html
{% extends 'dashboard-admin/dashboard.html' %}
{% load static %}

{% block content %}
	<div class="cards">
		<div class="card">
			<div class="content">
				<div class="pric">
					<h3>{{TOTAL_NET}} DH</h3>
					<p>REVENU NET TOTAL</p>
				</div>
				<i class="fa-solid fa-dollar-sign"></i>
			</div>
		</div>
		<div class="card">
			<div class="content">
				<div class="pric">
					<h3>{{total_packages}}</h3>
					<p>LES COLIES</p>
				</div>
				<i class="fa-solid fa-cube"></i>
			</div>
		</div>
		<div class="card">
			<div class="content">
				<div class="pric">
					<h3>{{MEN_DELIVERY}}</h3>
					<p>livraison hommes</p>
				</div>
				<i class="fa-solid fa-people-group"></i>
			</div>
		</div>
		<div class="card">
			<div class="content">
				<div class="pric">
					<h3>{{TOTAL_PACKAGE_DELIVERED}}</h3>
					<p>colis livrés</p>
				</div>
				<i class="fa-solid fa-truck-ramp-box"></i>
			</div>
		</div>
	</div>
	<div class="block container text-center mt-5 ">
		<!-- packages -->
		<div class="row justify-content-between flex-wrap">
			<div class="show-data packages col-7 mt-5">
				<div class="top">
					<h1>packages</h1>
				</div>
				<div class="body">
					<div class="filter">
						<form action="" method="GET">
							<input oninput="searchId(idSearch='search-package', idClass='id-package')" type="search" name="search-package" id="search-package" placeholder="search with id">
						</form>
					</div>
					<div class="content">
						<div class="package">
							<table class="table table-bordered table-hover">
								<thead>
									<tr>
										<th scope="col">ID</th>
										<th scope="col">Client</th>
										<th scope="col">Etat</th>
										<th scope="col">City</th>
										<th scope="col">Date</th>
										<th scope="col">Actions</th>
									</tr>
								</thead>
								<tbody >
									{% for package in packages %}
									<tr>
										<th scope="row" data="{{package.id_package}}" class="id id-package" id="ind">{{package.id_package}}</th>
										<td>{{package.client_name}}</td>
										{% if package.etat == "Ramassée"%}
											<td><span class="badge text-bg-warning">{{package.etat}}</span></td>
											{% elif package.etat == "Annulée"%}
											<td><span class="badge text-bg-danger">{{package.etat}}</span></td>
											{% elif package.etat == "Livrée"%}
											<td><span class="badge text-bg-success">{{package.etat}}</span></td>
											{% elif package.etat == "Pas de réponse"%}
											<td><span class="badge text-bg-info">{{package.etat}}</span></td>
											{% else %}
											<td><span class="badge text-bg-dark">{{package.etat}}</span></td>
											{% endif %}
										<td>{{package.city}}</td>
										<td>{{package.date_created}}</td>
										<td>
											<a href="{% url 'edite_package' package.user.id package.id_package %}"><i class='bx bx-message-square-edit'></i></a>
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
			<div class="show-data men-delivery col-4 mt-5 ">
				<div class="top">
					<h1>All Delivery</h1>
				</div>
				<div class="body">
					<div class="filter">
						<form action="" method="GET">
							<input type="search" name="search" id="search" placeholder="Search with username or company name">
						</form>
					</div>
					<div class="content">
						{% for item in data_admin %}
							{% for delivery in item.men_delivery.all %}
								<div class="user">
									<div class="info">
										<div class="logo">
											<img src="{% static 'img/profile/default_profile.png' %}" alt="">
										</div>
										<div class="username">
											<h4 class="name">{{delivery.first_name}}-{{delivery.last_name}}</h4>
											<p class="company-name">{{delivery.city}}</p>
										</div>
									</div>
									<div class="actions">
										<a href="{% url 'view_delivery' delivery.user.id %}"><i class='bx bx-show'></i></a>
									</div>
								</div>
							{% endfor %}
						{% endfor %}
					</div>
				</div>
				<!-- end packages -->
			</div>
		</div>
		<!-- end packages -->
		
	</div>
{% endblock content %}

templates/dashboard-admin/exchange.html
{% extends 'dashboard-admin/dashboard.html' %}
{% load static %}


{% block content %}
	<div class="dashboard">
		<div class="content">
			<div class="block container mt-5 ">
				<div class="row justify-content-center exchange">
					<form class="row g-3 col-9">
						<div class="col-md-6 mb-4">
							<label for="inputid" class="form-label">ID Package to exchange</label>
							<input type="text" class="form-control" id="inputid" value="{{exchange_data.exchange_id}}" disabled>
						</div>
						<div class="col-md-6 mb-4">
							<label for="inputarticle" class="form-label">Price</label>
							<input type="text" class="form-control" id="inputarticle" value="{{exchange_data.exchange_price}}" disabled>
						</div>
						<div class="col-md-12 h-100 mb-4">
							<label for="inputPackages" class="form-label">exchange</label>
							<textarea class="form-control h-100" id="validationTextarea" disabled >{{exchange_data.exchange}}</textarea>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

templates/dashboard-admin/packages.html
{% extends 'dashboard-admin/dashboard.html' %}
{% load static %}


{% block content %}
    <div class="dashboard">
        <div class="content">
            <div class="block container mt-5 ">
                <div class="row justify-content-center packages">
                    <form class="row g-3 col-9" method="POST">
                        {% csrf_token %}
                        {% if "admin" in request.user.groups.all|safeseq %}
                            <div class="col-md-6 mb-4">
                                <label for="inputId" class="form-label">ID Package</label>
                                {{formPackages.id_package}}
                            </div>
                            <div class="col-md-6 mb-4">
                                <label for="inputArticle" class="form-label">Article</label>
                                {{formPackages.article_name}}
                            </div>
                            <div class="col-12 mb-4">
                                <label for="inputAddress" class="form-label">Address</label>
                                {{formPackages.address}}
                            </div>
                            <div class="col-md-6 mb-4">
                                <label for="inputCity" class="form-label">City</label>
                                {{formPackages.city}}
                            </div>
                            <div class="col-6 mb-4">
                                <label for="inputnumber" class="form-label">Phone number</label>
                                {{formPackages.phone_number}}
                            </div>
                            <div class="col-6 mb-4">
                                <label for="inputClientname" class="form-label">Client name</label>
                                {{formPackages.client_name}}
                            </div>
                            <div class="col-6 mb-4">
                                <label for="inputDate" class="form-label">Date created</label>
                                {{formPackages.date_created}}
                            </div>
                            <div class="col-md-4 mb-4">
                                <label for="inputEtat" class="form-label">Etat</label>
                                {{formPackages.etat}}
                            </div>
                            <div class="col-md-4 mb-4">
                                <label for="inputPickedup" class="form-label">Received</label>
                                {{formPackages.picked_up}}
                            </div>
                            <div class="col-md-4 mb-4">
                                <label for="inputPrice" class="form-label">Price</label>
                                {{formPackages.price}}
                            </div>
                        {% elif "delivery" in  request.user.groups.all|safeseq %}
                            <div class="col-md-12 mb-4">
                                <label for="inputEtat" class="form-label">Etat</label>
                                {{formPackages.etat}}
                            </div>
                        {% else %}
                            <div class="col-md-6 mb-4">
                                <label for="inputEtat" class="form-label">Etat</label>
                                {{formPackages.etat}}
                            </div>
                            <div class="col-md-6 mb-4">
                                <label for="inputPickedup" class="form-label">Received</label>
                                {{formPackages.picked_up}}
                            </div>
                        {% endif %}
                        <div class="col-12">
                            <button type="submit" class="btn btn-outline-success col-12">Edite</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/dashboard-admin/received.html
{% extends 'dashboard-admin/dashboard.html' %}
{% load static %}

{% block content %}
    <div class="dashboard">
        <div class="content">
            <div class="block container mt-5 ">
                <div class="row justify-content-center received">
                    <form class="row g-3 col-9" method="POST">
                        {% csrf_token %}
                        <div class="col-md-6 mb-4">
                            <label for="inputid" class="form-label">ID Received</label>
                            {{formReceived.received_id}}
                        </div>
                        <div class="col-md-6 mb-4">
                            <label for="inputarticle" class="form-label">Date Received</label>
                            {{formReceived.date_received}}
                        </div>
                        <div class="col-md-12 mb-4">
                            <label for="inputPackages" class="form-label">Packages</label>
                            {{formReceived.packages}}
                        </div>
                        <div class="col-md-6 mb-4">
                            <label for="inputTotalamount" class="form-label">Total amount</label>
                            {{formReceived.total_amount}}
                        </div>
                        <div class="col-6 mb-4">
                            <label for="inputTotalwithdrawn" class="form-label">Total withdrawn</label>
                            {{formReceived.total_withdrawn}}
                        </div>
                        <div class="col-6 mb-4">
                            <label for="inputReceived" class="form-label">Receive</label>
                            {{formReceived.receive}}
                        </div>
                        <div class="col-md-6 mb-4">
                            <label for="inputPickedup" class="form-label">Invoices</label>
                            {{formReceived.invoise}}
                        </div>
                        <div class="col-12">
                            <button type="submit" class="btn btn-outline-success col-12">Edite</button>
                        </div>
                    </form>
                    <div class="row g-3 col-9 mt-4">
                        <div class="col-6">
                            <a href="{% url 'pdf_lables' received_update.user.id received_update.received_id%}"<button type="submit" class="btn btn-outline-primary col-12">Labels</button></a>
                        </div>
                        <div class="col-6">
                            <a href="#"><button type="submit" class="btn btn-outline-secondary col-12">Collection vouchers</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<script>
    const inputs = document.querySelectorAll("input");
    const selects = document.querySelectorAll("select")
    inputs.forEach(e => {
        e.classList.add("form-select")
    })
    selects.forEach(e => {
        e.classList.add("form-select")
    })
</script>

<script>
    $(document).ready(function () {
        $('#id_packages').selectize({
            sortField: 'text'
        });
    });
</script>
{% endblock content %}

templates/dashboard-admin/refund.html
{% extends 'dashboard-admin/dashboard.html' %}
{% load static %}
{% block content %}
	<div class="dashboard">
		<div class="content">
			<div class="block container mt-5 ">
				<div class="row justify-content-center refund">
					<form class="row g-3 col-9">
						<div class="col-md-6 mb-4">
							<label for="inputid" class="form-label">ID Package to refund</label>
							<input type="text" class="form-control" id="inputid" value="{{refund_data.refund_id}}" disabled>
						</div>
						<div class="col-md-6 mb-4">
							<label for="inputarticle" class="form-label">Price</label>
							<input type="text" class="form-control" id="inputarticle" value="{{refund_data.refund_price}}" disabled>
						</div>
						<div class="col-md-12 h-100 mb-4">
							<label for="inputPackages" class="form-label">Refund</label>
							<textarea class="form-control h-100" id="validationTextarea" disabled >{{refund_data.refund}}</textarea>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}